name: Deploy Extension

on:
  workflow_dispatch: ~
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached `tree-sitter-twig.wasm`.
        id: cache-tree-sitter-twig
        uses: actions/cache/restore@v3
        with:
          path: ./packages/tree-sitter-twig/tree-sitter-twig.wasm
          key: |
            tree-sitter-twig-${{ runner.os }}-${{
              hashFiles(
                'packages/tree-sitter-twig/grammar.js',
                'packages/tree-sitter-twig/package.json',
                'packages/tree-sitter-twig/(bindings|corpus|quieries|src)/**/*'
              )
            }}

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, "@vscode/vsce"]

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm run build --publish

      - name: Cache `tree-sitter-twig.wasm`.
        uses: actions/cache/save@v3
        with:
          path: ./packages/tree-sitter-twig/tree-sitter-twig.wasm
          key: ${{ steps.cache-tree-sitter-twig.outputs.cache-primary-key }}
